# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tvDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_name', models.CharField(max_length=150)),
                ('tv_description', models.CharField(max_length=250)),
                ('tv_location', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='filedetails',
            name='play_duration',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='filedetails',
            name='play_on_tv_id',
            field=models.CharField(default='TV-Default', max_length=50),
            preserve_default=False,
        ),
    ]
