# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20170808_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetails',
            name='play_duration',
            field=models.IntegerField(default=20, null=True),
        ),
    ]
