# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-30 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150)),
                ('display_from', models.DateField()),
                ('display_until', models.DateField()),
                ('display_on_tv_id', models.CharField(max_length=50)),
            ],
        ),
    ]
